### ISSUE TITLE
Wrong status labels

### ISSUE THREAD

**Issue by Zipliks** [themanyfaceddemon/Barotrauma_Modding_Tool#20]
Mod Manager shows that CS scripting is disabled
![image](https://github.com/user-attachments/assets/946d524e-10b8-4327-ba14-f0ab6ed7637c)

But it is enabled
![image](https://github.com/user-attachments/assets/11685e8a-f94e-4f52-8b93-5b218fc99dfd)

### Version
windows-latest-x64
[0.1.0a3](https://github.com/themanyfaceddemon/Barotrauma_Modding_Tool/releases/tag/0.1.0a3)

**Comment by themanyfaceddemon** [comment]
Oh fuck
